### ISSUE TITLE
Error Failed to initialize (SE Content Update of 10/14/2024)

### ISSUE THREAD

**Issue by NingyMD** [WesternGamer/ProperGPSMarkerScaling#3]
```
2024-10-15 16:55:54.089 - Thread:   1 ->  [PluginLoader] [Error] Failed to initialize WesternGamer/ProperGPSMarkerScaling|GPS Marker Scaling because of an error: HarmonyLib.HarmonyException: Patching exception in method null ---> System.ArgumentException: Undefined target method for patch method static System.Boolean ClientPlugin.Patches.MyHudMarkerRenderBase_AddTexturedQuad_String::Prefix(System.Single& halfWidth, System.Single& halfHeight)
   at HarmonyLib.PatchClassProcessor.PatchWithAttributes(MethodBase& lastOriginal, Boolean unpatch)
   at HarmonyLib.PatchClassProcessor.Patch()
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at ClientPlugin.Plugin.Init(Object gameInstance)
   at avaness.PluginLoader.PluginInstance.Init(Object gameInstance)
```

![image](https://github.com/user-attachments/assets/98168bda-8037-40a9-b7ed-3f2644ba03c7)

**Comment by WesternSpace** [comment]
Fixed in commit ca888baaae769a469ed6298e15667e7c7a215391
